# Build node.js application and run it
FROM node:16.9.0

RUN echo 'deb http://deb.debian.org/debian buster-backports main' >> /etc/apt/sources.list
RUN apt update && apt -o Debug::Acquire::http=true install wireguard-tools --assume-yes

WORKDIR /app
COPY package.json .
RUN npm install

COPY . .

CMD ["node", "server.js"]
